project:
  type: website

website:
  title: "Curso Introductorio de R"
  navbar:
    logo: images/cropped-mesi.png  # <- Ruta a tu logo
    left:
      - text: "Instalación"
        href: install.qmd
      - text: "Inicio"
        href: index.qmd
      - text: "Clase 1"
        href: clase_1.qmd
      - text: "Ejercicios"
        href: ejercicios.qmd

format:
  html:
    theme: cosmo
    toc: true
