---
title: "Ejercicios"
format: html
editor: visual
---

## Ejercicios \# 1

1.  Reiniciar R (Session → Restart R).

2.  Crear un nuevo script en su carpeta de trabajo nombrado `ejercicio_1.R` y realizar los siguientes procedimientos:

    -   Crear un objeto llamado `var` definido como el resultado de la suma: `3 + 9`.

    -   Crear un vector `vec` que contenga los números `1, 3, 5`.

    -   Crear tres vectores (`vec1`, `vec2`, `vec3`) que sean transformaciones del vector anterior.

    -   Crear tres vectores con la misma cantidad de elementos que `vec`, pero con variables de texto (`vec4`, `vec5`, `vec6`).

    -   Crear un data frame `data` como combinación de todos los vectores creados previamente.

    -   Crear una matriz diagonal de 2×2 que contenga `1` en la diagonal y `0` en el resto, y nombrar sus filas y columnas como `sec1`, `sec2`.

    -   Multiplicar la matriz diagonal por un vector columna de `1`.

    -   Exportar los resultados en formato CSV.
