---
title: "Instalación"
format: html
editor: visual
---

## 1. Instalación de R y RStudio

### Mac

1.  Abra un navegador y vaya a www.r-project.org.

2.  Haga clic en **download R** bajo “Getting Started”.

3.  Seleccione un espejo CRAN y haga clic en el enlace correspondiente.

4.  Haga clic en **Download R for (Mac) OS X**.

5.  Descargue el archivo `.pkg` de la versión más reciente (por ejemplo, R 4.1.1).

6.  Abra el archivo `.pkg` y siga las instrucciones del instalador.

7.  Una vez instalado R, descargue RStudio desde www.rstudio.com \> **Download Free Desktop IDE** \> **Desktop Open Source License** \> descargue la versión `.dmg` para Mac y arrástrela a la carpeta de Aplicaciones.

8.  Descargar e instalar Rtools <https://cran.r-project.org/bin/windows/Rtools/rtools45/rtools.html>

### Windows

1.  Abra un navegador y vaya a www.r-project.org.

2.  Haga clic en **download R** bajo “Getting Started”.

3.  Seleccione un espejo CRAN y haga clic en el enlace correspondiente.

4.  Haga clic en **Download R for Windows**.

5.  Descargue el instalador `.exe` de la versión más reciente (por ejemplo, R 4.1.1).

6.  Abra el archivo `.exe` y siga las instrucciones del instalador.

7.  Una vez instalado R, descargue RStudio desde www.rstudio.com \> **Download RStudio** \> **Desktop Open Source License** \> descargue la versión `.exe` para Windows y ejecútela.

8.  Descargar e instalar Rtools <https://cran.r-project.org/bin/windows/Rtools/rtools45/rtools.html>
